apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: rickhuihk/multi-client
      context: client
      sync:
        manual:
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: rickhuihk/multi-server
      context: server
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: rickhuihk/multi-worker
      context: worker
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-cluster-ip-service.yaml
